behaviors:
  Quoridor:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64  # Increased to handle more complex game states
      buffer_size: 10240  # Increased to store more experiences
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95  # Slightly reduced to balance between bias and variance
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256  # Increased to handle more complex game states
      num_layers: 3  # Added an extra layer for more processing depth
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 2000000  # Increased to allow for longer training
    time_horizon: 128  # Increased to capture longer-term dependencies
    summary_freq: 50000  # Increased due to longer training