behaviors:
  quoridor:
    trainer_type: ppo
    summary_freq: 15000
    time_horizon: 64
    max_steps: 1000000
    hyperparameters:
      learning_rate: 3.0e-4
      batch_size: 128
      buffer_size: 10240
      learning_rate_schedule: linear
      beta: 5.0e-3
    network_settings:
      hidden_units: 512
      num_layers: 2
      memory:
        memory_size: 64
        sequence_length: 32
    reward_signals:
      extrinsic:
        gamma: 0.995
      curiosity:
        gamma: 0.995
        strength: 0.01
    self_play:
      save_steps: 20000
      team_change: 100000
      play_against_latest_model_ratio: 0.5
