behaviors:
  quoridor:
    trainer_type: ppo
    summary_freq: 10000
    time_horizon: 64
    max_steps: 500000
    threaded: false
    hyperparameters:
      learning_rate: 3.0e-4
      batch_size: 64
      buffer_size: 10240
      learning_rate_schedule: linear
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
    network_settings:
      hidden_units: 256
      num_layers: 2
      normalize: false
      memory:
        memory_size: 64
        sequence_length: 32
    reward_signals:
      extrinsic:
        gamma: 0.995
      curiosity:
        strength: 0.01
        gamma: 0.995
    self_play:
      save_steps: 20000
      team_change: 100000

