behaviors:
  quoridor:
    trainer_type: ppo
    summary_freq: 50000
    time_horizon: 64
    max_steps: 10000000
    threaded: false
    hyperparameters:
      learning_rate: 2.0e-4
      batch_size: 64
      buffer_size: 10240
      learning_rate_schedule: linear
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
    network_settings:
      hidden_units: 512
      num_layers: 3
      normalize: false
      memory:
        memory_size: 128
        sequence_length: 64
    reward_signals:
      extrinsic:
        gamma: 0.995
      curiosity:
        gamma: 0.995
        strength: 0.02
    self_play:
      save_steps: 60000
      team_change: 300000
      play_against_latest_model_ratio: 0.6
